### ISSUE TITLE
How to seamlessly integrate model-driven mode & model-discovery-mode in a fully distributed context ?

### ISSUE THREAD

**Issue by iPlumb3r** [iPlumb3r/EntangledBootstrap#1]
Seems we get a 1st level of anwser thanks to Chris Gebhartd (from InfoCentral : https://infocentral.org/)
See this Twitter Thread : https://twitter.com/ChrisGebhardtIC/status/1230929932139814913

**Comment by gyuri-lajos** [comment]
This is just a quick note. I cannot ressist the invitation to write about it.
I like most been circling the knowledge based software engineering dream.
Had many successful practical experiments in building graph based models where the edges can be associated with arbitrary computations. Even  implemented a morphic Business Processer Modeller and generated project planners, issue trackers and such like,

My bent has always been more heuristic and seeking ways for emergent situated transitional "ontologies".
Lately I am doing experiments in graph based digital articulation using "Linked Text"
https://jrnl.global/2018/11/20/linked-text/

The concept evolved a lot since. The latest is the idea that instead of top down elaboration we can try to introduce systematically back links to indicate adjacent contexts and create nodes with an indication of the  intent/aspect we had in mind by picking/designating and elaborating the meaning of one specific incoming link, even if nothing that would be source has been specified yet.

The expectation is that models can emerge when in a separate meta level consolidation work is carried out. This way we can mean more then we could say initially.

This is particulary important in contexts that are not fully articulated, or could never be as everything is deeply intertwingled.
The expectation is that at least that this  heuristic proces can allow us to move from the informal/incompeltely articualted to the more articualte/formal and a way to get to produce effective descriptions that can be executed eventually.

**Comment by gyuri-lajos** [comment]
When it comes to collaboration and accessing work and do reconciliation two things help.
One at every point in the articulation automatic entity resolution is taking place. So whenever is feasible once welf introduced entities are linked to notable ones whenever possible.
This is the key to be able to surface and present to the knowledge worker relevant contexts where reconciliation needed.
The problem with elaboration is that the more you elaborate the more commitments one makes to elaborate more. It is in the conciliation phase, making sense of and inducing order at the meta level specifically working with the meaning of connections that can introduce more order.

I punt the mapping between truly incommensurate conceptualization in favor of seeing this approach to be effective in having conversations that eventually lead to working software and use these heuristic techniques to enable us to write software where we can change our minds and conceptualizations and have the consequences reverberate automatically, thus avoiding programming ourselves into a corner.

I have I hopes attached to this approach. One things is for sure as of know, this way of working provides ample shifts of perspectives to act as a serendipity engine, and does help to bring to mind what we had in mind ever if we lack the capacity to recall the required search term.

Add to all this that in the decentralized world I envisage contributors own their own contributions, and every "nugget" of information has its own immutable high resolution address. So when anybody links to anything, or transclude *(with transcopyright) anything,  a two way link is created and thus the context from anything that is linked or transcluded remains addressable.

https://hub.opidox.com/pdfs/FoT%202020%20Gyuri%20Lajos.pdf

**Comment by gyuri-lajos** [comment]
I hope it is not completely incomprehensible or deemed inapproapriate.

**Comment by iPlumb3r** [comment]
A little bit abstract, but potentially useful.
In order to be relevant, software previously requires a deep conceptualization process ;-)

**Comment by gyuri-lajos** [comment]
In order to be relevant, software previously requires a deep
conceptualization process ;-)
Could not agree more.

I was wondering, had you worked with LISP or Smalltalk in your career?

Cheers

Gyuri

**Comment by iPlumb3r** [comment]
No, never. I'm could say I had NOT at all technical skills in any computer languages ...

**Comment by iPlumb3r** [comment]
https://forum.holochain.org/t/technical-properties-of-decentralized-information-according-infocentral/1539/10

**Comment by iPlumb3r** [comment]
Just migrated this issue into the more generic Ecosystem Mapping initiative : https://github.com/iPlumb3r/EcosystemMapping/issues/1
